# Generated by Django 5.1.6 on 2025-05-18 13:30

import django.db.models.deletion
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Centers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('phone', models.IntegerField(max_length=15, null=True)),
                ('location', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('description', models.TextField(max_length=400, null=True)),
                ('course_overview', models.TextField(max_length=400, null=True)),
                ('what_you_will_learn', models.TextField(max_length=800, null=True)),
                ('requirments', models.TextField(max_length=200, null=True)),
                ('course_duration', models.TextField(max_length=200, null=True)),
                ('session_duration', models.TextField(max_length=200, null=True)),
                ('level', models.IntegerField(max_length=5, null=True)),
                ('price', models.IntegerField(max_length=10, null=True)),
                ('maxNmberofstudents', models.IntegerField(max_length=20, null=True)),
                ('CourseStatus', models.CharField(choices=[('Online Course', 'Online'), ('On-Site Course', 'Offline')], max_length=50, null=True)),
                ('age', multiselectfield.db.fields.MultiSelectField(choices=[('5-7', '5-7'), ('7-9', '7-9'), ('9-11', '9-11'), ('9-11', '9-11'), ('11-13', '11-13'), ('13+', '13+')], max_length=50)),
                ('category', models.CharField(choices=[('Programming', 'Programming'), ('Robotics', 'Robotics'), ('Strong Mind', 'Strong Mind')], max_length=50, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('is_active', models.CharField(choices=[('Active Now', 'Active Now'), ('Coming Soon', 'Coming Soon')], max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Instractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('phone', models.IntegerField(max_length=15, null=True)),
                ('location', models.CharField(max_length=50, null=True)),
                ('paymentMethod', models.CharField(max_length=20, null=True)),
                ('courses', models.ManyToManyField(to='common_App.courses')),
            ],
        ),
        migrations.CreateModel(
            name='OngoingCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WeekDay', models.CharField(max_length=50, null=True)),
                ('startDate', models.DateField()),
                ('paymentMethod', models.CharField(max_length=20, null=True)),
                ('sessionNumber', models.IntegerField(max_length=10, null=True)),
                ('courseID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common_App.courses')),
                ('instractor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common_App.instractor')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common_App.centers')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('phone', models.IntegerField(max_length=15, null=True)),
                ('dateofbirth', models.DateField()),
                ('school', models.CharField(max_length=50, null=True)),
                ('grade', models.CharField(max_length=50, null=True)),
                ('parentContact', models.IntegerField(max_length=15, null=True)),
                ('address', models.TextField(max_length=200, null=True)),
                ('studentID', models.IntegerField(max_length=15, null=True)),
                ('Enrolled_Course', models.ManyToManyField(to='common_App.ongoingcourses')),
            ],
        ),
        migrations.CreateModel(
            name='ToolKit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kitID', models.IntegerField(max_length=10, null=True)),
                ('level', models.IntegerField(max_length=5, null=True)),
                ('details', models.TextField(max_length=1000, null=True)),
                ('price', models.IntegerField(max_length=50, null=True)),
                ('components', models.ManyToManyField(to='common_App.component')),
            ],
        ),
        migrations.AddField(
            model_name='courses',
            name='kitId',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common_App.toolkit'),
        ),
    ]
