# Generated by Django 5.1.6 on 2025-05-18 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='parentContact',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='studentID',
            field=models.IntegerField(null=True),
        ),
    ]
