# Generated by Django 5.1.6 on 2025-05-18 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_App', '0002_alter_student_parentcontact_alter_student_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='level',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='courses',
            name='maxNmberofstudents',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='courses',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='instractor',
            name='phone',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ongoingcourses',
            name='sessionNumber',
            field=models.IntegerField(null=True),
        ),
    ]
