# Generated by Django 5.1.6 on 2025-03-12 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_App', '0002_courses_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
