# Generated by Django 5.1.6 on 2025-03-16 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_App', '0003_courses_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='CourseStatus',
            field=models.CharField(choices=[('Online', 'Online Course'), ('Offline', 'On-Site Course')], max_length=50, null=True),
        ),
    ]
