# Generated by Django 5.1.6 on 2025-03-16 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_App', '0004_courses_coursestatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='CourseStatus',
            field=models.CharField(choices=[('Online Course', 'Online'), ('On-Site Course', 'Offline')], max_length=50, null=True),
        ),
    ]
