# Generated by Django 5.1.6 on 2025-05-19 05:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_App', '0004_alter_centers_phone_alter_toolkit_kitid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instractor',
            name='paymentMethod',
        ),
        migrations.AddField(
            model_name='ongoingcourses',
            name='end_time',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AddField(
            model_name='ongoingcourses',
            name='start_time',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AlterField(
            model_name='ongoingcourses',
            name='WeekDay',
            field=models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], default='MON', max_length=3),
        ),
    ]
