# Generated by Django 5.1.6 on 2025-03-19 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common_App', '0005_alter_courses_coursestatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='minAge',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='status',
        ),
    ]
