# Generated by Django 5.1.7 on 2025-05-19 07:21

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common_App', '0005_remove_instractor_paymentmethod_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='age',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('5-7', '5-7'), ('7-9', '7-9'), ('9-11', '9-11'), ('11-13', '11-13'), ('13+', '13+')], max_length=50),
        ),
    ]
