# Generated by Django 5.1.6 on 2025-03-19 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_App', '0006_remove_courses_minage_remove_courses_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='age',
            field=models.CharField(choices=[('5-7', '5-7'), ('7-9', '7-9'), ('9-11', '9-11'), ('11-13', '11-13')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='courses',
            name='category',
            field=models.CharField(choices=[('Programming', 'Programming'), ('Robotics', 'Robotics'), ('Strong Mind', 'Strong Mind')], max_length=50, null=True),
        ),
    ]
