# Generated by Django 5.1.7 on 2025-05-19 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_App', '0006_alter_courses_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='paid_fees',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='paying_image',
            field=models.ImageField(blank=True, null=True, upload_to='student_images/'),
        ),
    ]
