# Generated by Django 5.1.6 on 2025-03-21 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_App', '0007_courses_age_courses_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='is_active',
            field=models.CharField(choices=[('Active Now', 'Active Now'), ('Coming Soon', 'Coming Soon')], max_length=50, null=True),
        ),
    ]
