# Generated by Django 5.1.6 on 2025-05-20 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_App', '0007_student_paid_fees_student_paying_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='ongoingcourses',
            name='age',
            field=models.CharField(choices=[('5-7', '5-7'), ('7-9', '7-9'), ('9-11', '9-11'), ('11-13', '11-13'), ('13+', '13+')], default='5-7', max_length=6),
        ),
    ]
