# Generated by Django 5.1.7 on 2025-03-23 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_App', '0008_courses_course_duration_courses_course_overview_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='course_duration',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='courses',
            name='course_overview',
            field=models.TextField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='courses',
            name='description',
            field=models.TextField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='courses',
            name='session_duration',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='courses',
            name='what_you_will_learn',
            field=models.TextField(max_length=400, null=True),
        ),
    ]
