# Generated by Django 5.1.6 on 2025-05-20 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_App', '0008_ongoingcourses_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='hours_per_month',
            field=models.IntegerField(null=True),
        ),
    ]
