# Generated by Django 5.1.7 on 2025-03-23 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_App', '0009_alter_courses_course_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='what_you_will_learn',
            field=models.TextField(max_length=800, null=True),
        ),
    ]
